name: Deploy Backend to Azure

on:
  push:
    branches: [ main ]
    paths:
      - 'backend/**'
      - '.github/workflows/deploy-backend.yml'

env:
  AZURE_WEBAPP_NAME: survey-aggregator-backend
  NODE_VERSION: '20.x'

jobs:
  deploy-backend:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
    
    - name: Install backend dependencies
      run: |
        cd backend
        npm ci --production
    
    - name: Create deployment package
      run: |
        cd backend
        zip -r ../backend-deploy.zip . -x "node_modules/.cache/*"
    
    - name: Deploy via Kudu API
      run: |
        # Extract publish profile credentials
        echo "${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}" > publish-profile.xml
        USERNAME=$(grep -o 'userName="[^"]*"' publish-profile.xml | cut -d'"' -f2)
        PASSWORD=$(grep -o 'userPWD="[^"]*"' publish-profile.xml | cut -d'"' -f2)
        
        # Deploy using curl with retries
        for i in {1..3}; do
          echo "Deployment attempt $i..."
          if curl -X POST \
            -u "$USERNAME:$PASSWORD" \
            "https://${{ env.AZURE_WEBAPP_NAME }}.scm.azurewebsites.net/api/zipdeploy?isAsync=true" \
            -T backend-deploy.zip \
            -H "Content-Type: application/zip" \
            --max-time 300 \
            --retry 3 \
            --retry-delay 10; then
            echo "Deployment successful!"
            break
          else
            echo "Deployment attempt $i failed, retrying..."
            sleep 30
          fi
        done
