name: Deploy to Vercel via GitHub

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm ci
      - run: npm run build
        env:
          CI: false
          DISABLE_ESLINT_PLUGIN: true
          GENERATE_SOURCEMAP: false
      - name: Configure Git user
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
      - name: Commit and push to GitHub
        run: |
          git add .
          git commit -m "Build for Vercel deployment [skip ci]" || echo "No changes to commit"
          git push origin main
      - name: Notify deployment
        run: |
          echo "✅ Build completed and pushed to GitHub!"
          echo "🚀 Vercel will automatically deploy from GitHub repository"
          echo "📱 Check your Vercel dashboard for deployment status" 