name: Simple Deploy to Azure

on:
  push:
    branches: [ main ]

jobs:
  deploy-backend:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
    
    - name: Install backend dependencies
      run: |
        cd backend
        npm ci --production
    
    - name: Create deployment package
      run: |
        cd backend
        zip -r ../backend-deploy.zip . -x "node_modules/.cache/*"
    
    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v3
      with:
        app-name: survey-aggregator-backend
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: backend-deploy.zip

  deploy-frontend:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
    
    - name: Install frontend dependencies
      run: npm ci
    
    - name: Build frontend (skip linting)
      run: |
        # Completely bypass all linting and TypeScript checking
        export CI=false
        export DISABLE_ESLINT_PLUGIN=true
        export GENERATE_SOURCEMAP=false
        export SKIP_PREFLIGHT_CHECK=true
        export TSC_COMPILE_ON_ERROR=true
        npm run build:ci
      env:
        REACT_APP_API_URL: https://survey-aggregator-backend.azurewebsites.net/api
        CI: false
        DISABLE_ESLINT_PLUGIN: true
        GENERATE_SOURCEMAP: false
        SKIP_PREFLIGHT_CHECK: true
        TSC_COMPILE_ON_ERROR: true
    
    - name: Deploy to Azure Static Web Apps
      uses: Azure/static-web-apps-deploy@v1
      with:
        azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        app_location: "/"
        output_location: "build"
        skip_app_build: true
        action: "upload"
